version: 2.1

jobs:
  test:
    docker:
      - image: ghcr.io/cirruslabs/flutter:3.38.5
    steps:
      - checkout
      - run:
          name: Get Flutter dependencies
          command: flutter pub get
      - run:
          name: Run tests inside app
          command: flutter test

  build-apk:
    docker:
      - image: ghcr.io/cirruslabs/flutter:3.38.5
    steps:
      - checkout
      - run:
          name: Get Flutter dependencies
          command: flutter pub get
      - run:
          name: Build release APK
          command: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
          destination: app-release.apk

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build-apk:
          requires:
            - test